-- Creation du schema du projet
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTO_INCREMENT, name VARCHAR, price NUMERIC, weight NUMERIC);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTO_INCREMENT, status VARCHAR);
CREATE TABLE IF NOT EXISTS orders_content(order_id INTEGER AUTO_INCREMENT, product_id INTEGER);